/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2018-08-05 10:37:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class compose_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Compose</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/ediagnostic/bootstrapfiles/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("<script src=\"/ediagnostic/bootstrapfiles/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/ediagnostic/bootstrapfiles/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"/ediagnostic/js/validation.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function()\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t{\r\n");
      out.write("      $(\"#txtrid\").blur(\r\n");
      out.write("      \t\tfunction(){\r\n");
      out.write("      \t\t\tvar rid=this.value;\r\n");
      out.write("      \t\t\t//alert(ui)\r\n");
      out.write("      \t\t\t $.get(\"/ediagnostic/jsp/recidcheck.jsp\",\r\n");
      out.write("      \t\t\t        {\r\n");
      out.write("      \t\t\t          recid:rid\r\n");
      out.write("      \t\t\t          \r\n");
      out.write("      \t\t\t        },\r\n");
      out.write("      \t\t\t        function(data,status){\r\n");
      out.write("      \t\t\t        \t//if(data==\"\")\r\n");
      out.write("      \t\t\t          //  alert(\"Data: \" + data + \"\\nStatus: \" + status);\r\n");
      out.write("      \t\t\t             $(\"#div1\").html(data);\r\n");
      out.write("      \t\t\t             $(\"#div1\").show();\r\n");
      out.write("      \t\t\t             //$(\"#div1\").hide(5000);\r\n");
      out.write("      \t\t\t             \r\n");
      out.write("      \t\t\t        });\r\n");
      out.write("      \t\t\t\r\n");
      out.write("      \t\t\t\r\n");
      out.write("      \t\t\t\r\n");
      out.write("      });\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("\tfunction main() {\r\n");
      out.write("\t\tvar usid = document.getElementById(\"txtsid\").value;\r\n");
      out.write("\t\tvar urid = document.getElementById(\"txtrid\").value;\r\n");
      out.write("\t\tvar usubject = document.getElementById(\"txtsubject\").value;\r\n");
      out.write("\t\tvar umsg = document.getElementById(\"txtmsg\").value;\r\n");
      out.write("\t\tvar b = true\r\n");
      out.write("\t\tif (checkEmpty(usid) == false) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"msgsid\").innerHTML = \"Please enter sender id\"\r\n");
      out.write("\t\t\tdocument.getElementById(\"txtsid\").focus()\r\n");
      out.write("\t\t\tb = false\r\n");
      out.write("\t\t} else if (checkEmpty(usid) == true) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"msgsid\").innerHTML = \"\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (checkEmpty(urid) == false) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"msgrid\").innerHTML = \"Please enter receiver id\"\r\n");
      out.write("\t\t\tdocument.getElementById(\"txtrid\").focus()\r\n");
      out.write("\t\t\tb = false\r\n");
      out.write("\t\t} else if (checkEmpty(urid) == true) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"msgrid\").innerHTML = \"\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (checkEmpty(usubject) == false) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"msgsubject\").innerHTML = \"Please enter your subject\"\r\n");
      out.write("\t\t\tdocument.getElementById(\"txtsubject\").focus()\r\n");
      out.write("\t\t\tb = false\r\n");
      out.write("\t\t} else if (checkEmpty(usubject) == true) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"msgsubject\").innerHTML = \"\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (checkEmpty(umsg) == false) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"msg\").innerHTML = \"Please enter your msg\"\r\n");
      out.write("\t\t\tdocument.getElementById(\"txtmsg\").focus()\r\n");
      out.write("\t\t\tb = false\r\n");
      out.write("\t\t} else if (checkEmpty(umsg) == true) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"msg\").innerHTML = \"\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn b\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-image: url('/ediagnostic/images/cmp.png');\">\r\n");
      out.write("\t");

		HttpSession hs = request.getSession(false);
		String uid = (String) hs.getAttribute("userkey");
	
      out.write("\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tstyle=\"width: 60%; height: 450px; background-color: transparent; margin-left: 20%; margin-right: 20%; border-radius: 10px;\">\r\n");
      out.write("\t\t<span id=\"isE\"></span>\r\n");
      out.write("\t\t<form action=\"/ediagnostic/Compose1\" method=\"post\"\r\n");
      out.write("\t\t\tonsubmit=\"return main()\">\r\n");
      out.write("\t\t\t<table align=\"center\" style=\"margin-left: 250px; margin-top: 100px\">\r\n");
      out.write("\t\t\t\t<tr style=\"height: 50px\">\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 150px\">Sender ID</th>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"text\" id=\"txtsid\" name=\"txtsid\"\r\n");
      out.write("\t\t\t\t\t\treadonly=\"readonly\" value=");
      out.print(uid);
      out.write("></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr><td style=\"color: red\" colspan=\"2\" id=\"msgsid\"></td></tr>\r\n");
      out.write("\t\t\t\t<tr style=\"height: 50px\">\r\n");
      out.write("\t\t\t\t\t<th>Receiver ID</th>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"text\" id=\"txtrid\" name=\"txtrid\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Enter Receiver ID\" onblur=\"checkExist()\"></th>\r\n");
      out.write("\t\t\t\t\t\t<th id=\"div1\" style=\"width: 100%; height: 100px\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr><td style=\"color: red; \" colspan=\"2\" id=\"msgrid\"></td></tr>\r\n");
      out.write("\t\t\t\t<tr style=\"height: 50px\">\r\n");
      out.write("\t\t\t\t\t<th>Subject</th>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"text\" id=\"txtsubject\" name=\"txtsubject\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Enter your subject\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr><td style=\"color: red\" colspan=\"2\" id=\"msgsubject\"></td></tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>Message</th>\r\n");
      out.write("\t\t\t\t\t<th><textarea id=\"txtmsg\" name=\"txtmsg\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Enter your message\" cols=\"25\" rows=\"5\"></textarea></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr><td style=\"color: red\" colspan=\"2\" id=\"msg\"></td></tr>\r\n");
      out.write("\t\t\t\t<tr style=\"height: 50px\">\r\n");
      out.write("\t\t\t\t\t<td align=\"center\"><input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-success\">\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\"><button type=\"button\" class=\"btn btn-danger\"><a href=\"/ediagnostic/Logoff\">Log Out</a></button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<!-- <div id=\"div1\" style=\"color: red ;width: 100%; height: 100px\"></div> -->\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
