/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2018-08-05 10:09:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import ediagnostic.dbtasks.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("ediagnostic.dbtasks");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/ediagnostic/bootstrapfiles/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("<script src=\"/ediagnostic/bootstrapfiles/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/ediagnostic/bootstrapfiles/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* Make the image fully responsive */\r\n");
      out.write(".carousel-inner img {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id= \"top\" style=\"width: 100%; height: 70px; float: left;\">\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tstyle=\"background-color: #F8F8F8; width: 60%; height: 70px; float: left; font-size: 40px; color: red;\">\r\n");
      out.write("\t\t<a href=\"/ediagnostic/jsp/home.jsp\"><img src=\"/ediagnostic/images/logo mini.png\"\r\n");
      out.write("\t\t\tstyle=\"margin-left: 5%; width: 30%; height: 65px;\"></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tstyle=\"width: 40%; height: 70px; float: left; background-color: #F8F8F8;\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div style=\"width: 80px; float: left; margin-top: 5px\">\r\n");
      out.write("\t\t\t<a href=\"/ediagnostic/html/contactus.html\">Contact Us</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"width: 70px; float: left; margin-top: 5px; margin-left: 10px\">\r\n");
      out.write("\t\t\t<a href=\"/ediagnostic/jsp/login.jsp\" class=\"btn btn-info\" role=\"button\">Sign In</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"width: 80px; float: left; margin-top: 5px; margin-left: 10px\">\r\n");
      out.write("\t\t\t<a href=\"/ediagnostic//jsp/patient_registration.jsp\" class=\"btn btn-info\" role=\"button\">Sign Up</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"width: 160px; float: left; margin-top: 5px; margin-left: 10px\">\r\n");
      out.write("\t\t\t<a href=\"/ediagnostic//jsp/viewtests.jsp\" class=\"btn btn-info\" role=\"button\">View available tests</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"width: 100%;height:500px;\">\r\n");
      out.write("<div style=\"width:20%; height:500px; float:left;\">\r\n");
      out.write("<center>News</center>\r\n");
      out.write("<ul style=\"list-style-type: none\">\r\n");
      out.write("\t\t");

		String strsql="select * from news order by date desc limit 5";
		ResultSet rs=CrudOperation.fetchData(strsql);
		while(rs.next())
		{
			String t=rs.getString("title");
			String id=rs.getString("newsid");
		
      out.write("\r\n");
      out.write("\t\t<li><a href=\"/ediagnostic/jsp/shownews.jsp?id=");
      out.print(id);
      out.write('"');
      out.write('>');
      out.print(t);
      out.write("</a></li>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"demo\" class=\"carousel slide\" data-ride=\"carousel\" style=\"width:60%; height:500px; float:left; border-radius: 15px\">\r\n");
      out.write("  <ul class=\"carousel-indicators\">\r\n");
      out.write("    <li data-target=\"#demo\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("    <li data-target=\"#demo\" data-slide-to=\"1\"></li>\r\n");
      out.write("    <li data-target=\"#demo\" data-slide-to=\"2\"></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  <div class=\"carousel-inner\">\r\n");
      out.write("    <div class=\"carousel-item active\">\r\n");
      out.write("      <img src=\"/ediagnostic/images/i1.jpg\" alt=\"Los Angeles\" width=\"1100\" height=\"500px\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img src=\"/ediagnostic/images/i2.jpg\" alt=\"Chicago\" width=\"1100\" height=\"500px\">\r\n");
      out.write("      <div class=\"carousel-caption\">\r\n");
      out.write("       \r\n");
      out.write("      </div>   \r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img src=\"/ediagnostic/images/i3.jpg\" alt=\"New York\" width=\"1100\" height=\"500px\">\r\n");
      out.write("      <div class=\"carousel-caption\">\r\n");
      out.write("       \r\n");
      out.write("      </div>   \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <a class=\"carousel-control-prev\" href=\"#demo\" data-slide=\"prev\">\r\n");
      out.write("    <span class=\"carousel-control-prev-icon\"></span>\r\n");
      out.write("  </a>\r\n");
      out.write("  <a class=\"carousel-control-next\" href=\"#demo\" data-slide=\"next\">\r\n");
      out.write("    <span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("  </a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:20%; height:500px; float:left;\">\r\n");
      out.write("<center>Tips</center>\r\n");
      out.write("<ul style=\"list-style-type: none\">\r\n");
      out.write("\t\t");

		String str2="select * from tips order by date desc limit 5";
		ResultSet rs2=CrudOperation.fetchData(str2);
		while(rs2.next())
		{
			String t=rs2.getString("subject");
			String id=rs2.getString("tipid");
		
      out.write("\r\n");
      out.write("\t\t<li><a href=\"/ediagnostic/jsp/showtips.jsp?id=");
      out.print(id);
      out.write('"');
      out.write('>');
      out.print(t);
      out.write("</a></li>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<a href=\"#top\">Go to top</a>\r\n");
      out.write("<script src=\"/ediagnostic/bootstrapfiles/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/ediagnostic/bootstrapfiles/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
