/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2018-08-04 17:58:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/ediagnostic/bootstrapfiles/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("<script src=\"/ediagnostic/bootstrapfiles/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/ediagnostic/bootstrapfiles/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"/ediagnostic/js/validation.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction main() {\r\n");
      out.write("\t\tvar ui = document.getElementById(\"txtuserid\").value;\r\n");
      out.write("\t\tvar upass = document.getElementById(\"txtuserpass\").value;\r\n");
      out.write("\t\tvar b = true\r\n");
      out.write("\t\tif (checkEmpty(ui) == false) {\r\n");
      out.write("\t\t\t/* alert(\"USerID needed\") */\r\n");
      out.write("\t\t\tdocument.getElementById(\"msgid\").innerHTML = \"Please enter user id\"\r\n");
      out.write("\t\t\tdocument.getElementById(\"txtuserid\").focus()\r\n");
      out.write("\t\t\tb = false\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (checkEmpty(ui) == true) {\r\n");
      out.write("\t\t\t/* alert(\"USerID needed\") */\r\n");
      out.write("\t\t\tdocument.getElementById(\"msgid\").innerHTML = \"\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (checkEmpty(upass) == false) {\r\n");
      out.write("\t\t\t//alert(\"User Password needed\")\r\n");
      out.write("\t\t\tdocument.getElementById(\"msgpass\").innerHTML = \"Please enter user password\"\r\n");
      out.write("\t\t\tdocument.getElementById(\"txtuserpass\").focus()\r\n");
      out.write("\t\t\tb = false\r\n");
      out.write("\t\t} else if (checkLength(upass) == false) {\r\n");
      out.write("\t\t\t//alert(\"Please enter password length of 9 or more characters\")\r\n");
      out.write("\t\t\tdocument.getElementById(\"msgpass\").innerHTML = \"Password length should be > 8 characters\"\r\n");
      out.write("\t\t\tdocument.getElementById(\"txtuserpass\").focus()\r\n");
      out.write("\t\t\tb = false\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn b\r\n");
      out.write("\t\t//alert(ui)\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-image: url('/ediagnostic/images/i1.jpg');\">\r\n");
      out.write("\t");

		String ms = (String) request.getAttribute("msg");
	
      out.write("\r\n");
      out.write("\t<div style=\"width: 55%; height: 200px; float: left; font-size: 40px; margin-left: 5%; color: red;\">E-Diagnostic Portal</div>\r\n");
      out.write("\t<div style=\"width: 40%; height: 200px; float: left\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div style=\"width: 80px; float: left; margin-top: 5px\">\r\n");
      out.write("\t\t\t<a href=\"/ediagnostic/jsp/home.jsp\">Home</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"width: 100px; float: left; margin-top: 5px; margin-left: 10px\">\r\n");
      out.write("\t\t\t<a href=\"/ediagnostic/html/contactus.html\">Contact Us</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tstyle=\"width: 60%; margin-left: 20%; margin-right: 20%; height: 100%; float: left;\">\r\n");
      out.write("\t\t<form action=\"/ediagnostic/Login1\" method=\"post\"\r\n");
      out.write("\t\t\tonsubmit=\"return main()\">\r\n");
      out.write("\t\t\t<table align=\"center\" style=\"margin-top: 50px;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 100px\">User ID</th>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"text\" id=\"txtuserid\" name=\"txtuserid\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Enter UserID\" autofocus=\"autofocus\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr style=\"height: 50px\">\r\n");
      out.write("\t\t\t\t\t<th>Password</th>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"password\" id=\"txtuserpass\" name=\"txtuserpass\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Enter password\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\" colspan=\"2\" style=\"height: 50px\"><button type=\"submit\">Login</button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t");

				if (ms != null) {
			
      out.write("\r\n");
      out.write("\t\t\t<h2 style=\"color: red;\">");
      out.print(ms);
      out.write("</h2>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h5 id=\"msgid\" style=\"color: red\"></h5>\r\n");
      out.write("\t\t\t<h5 id=\"msgpass\" style=\"color: red\"></h5>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
