/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2018-08-01 08:02:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class patientreport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/html/worker_menu.html", Long.valueOf(1533103327077L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Patient Report</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/ediagnostic/bootstrapfiles/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("<script src=\"/ediagnostic/bootstrapfiles/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/ediagnostic/bootstrapfiles/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"/ediagnostic/js/validation.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction main() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar workerid = document.getElementById(\"txtworkerid\").value;\r\n");
      out.write("\t\tvar patientname = document.getElementById(\"txtpatientname\").value;\r\n");
      out.write("\t\tvar testid = document.getElementById(\"txttestid\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar doctorid = document.getElementById(\"txtdoctorid\").value;\r\n");
      out.write("\t\tvar remark = document.getElementById(\"txtremark\").value;\r\n");
      out.write("\t\tvar status = document.getElementById(\"txtstatus\").value;\r\n");
      out.write("\t\tvar b = true\r\n");
      out.write("\r\n");
      out.write("\t\tif (checkEmpty(patientname) == false) {\r\n");
      out.write("\t\t\t//alert(\"userpass needed\")\r\n");
      out.write("\t\t\t    document.getElementById(\"msgname\").innerHTML = \"Patient Name required\"\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"txtpatientname\").focus()\r\n");
      out.write("\t\t\tb = false\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if (checkEmpty(patientname) == true) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"msgname\").innerHTML = \"\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (checkEmpty(testid) == false) {\r\n");
      out.write("\t\t\t//alert(\"userpass needed\")\r\n");
      out.write("\t\t\t    document.getElementById(\"msgid2\").innerHTML = \"test Id required\"\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"txttestid\").focus()\r\n");
      out.write("\t\t\tb = false\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if (checkEmpty(testid) == true) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"msgid2\").innerHTML = \"\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (checkEmpty(doctorid) == false) {\r\n");
      out.write("\t\t\t//alert(\"userpass needed\")\r\n");
      out.write("\t\t\t    document.getElementById(\"msgid3\").innerHTML = \"Doctor ID required\"\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"txtdoctorid\").focus()\r\n");
      out.write("\t\t\tb = false\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if (checkEmpty(doctorid) == true) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"msgid3\").innerHTML = \"\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (checkEmpty(remark) == false) {\r\n");
      out.write("\t\t\t//alert(\"userpass needed\")\r\n");
      out.write("\t\t    document.getElementById(\"msgremark\").innerHTML = \"Remark is required\"\r\n");
      out.write("\t\t\tdocument.getElementById(\"txtremark\").focus()\r\n");
      out.write("\t\tb = false\r\n");
      out.write("\t}\r\n");
      out.write("\telse if (checkEmpty(remark) == true) {\r\n");
      out.write("\t\tdocument.getElementById(\"msgremark\").innerHTML = \"\"\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (checkEmpty(status) == false) {\r\n");
      out.write("\t\t\t//alert(\"userpass needed\")\r\n");
      out.write("\t\t    document.getElementById(\"msgstatus\").innerHTML = \"Status is required\"\r\n");
      out.write("\t\t\tdocument.getElementById(\"txtstatus\").focus()\r\n");
      out.write("\t\tb = false\r\n");
      out.write("\t}\r\n");
      out.write("\telse if (checkEmpty(status) == true) {\r\n");
      out.write("\t\tdocument.getElementById(\"msgstatus\").innerHTML = \"\"\r\n");
      out.write("\t}\r\n");
      out.write("\t\treturn b\r\n");
      out.write("\t\t//alert(ui)\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

HttpSession hs = request.getSession(false);
String uid = (String) hs.getAttribute("userkey");

      out.write("\r\n");
      out.write("<div\r\n");
      out.write("\t\tstyle=\"width: 100%; height: 80px; background-color: #6882d1; float: left\">\r\n");
      out.write("\t\t<h1 style=\"text-align: center;\">Upload Patient Report</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"width: 20%; height: 700px; float: left\">\r\n");
      out.write("\t\t");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Patient Menu</title>\r\n");
      out.write("</head>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/ediagnostic/bootstrapfiles/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("<script src=\"/ediagnostic/bootstrapfiles/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/ediagnostic/bootstrapfiles/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"/ediagnostic/js/validation.js\"></script>\r\n");
      out.write("<body>\r\n");
      out.write("<ul style=\"list-style-type: none;\">\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic/jsp/upload.jsp\">Upload Profile Pic</a></li><br>\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic/jsp/compose.jsp\">Compose</a></li><br>\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic/jsp/inbox.jsp\">Inbox</a></li><br>\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic/jsp/sentitems.jsp\">Sent Items</a></li><br>\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic/jsp/viewworkerprofile.jsp\">View Profile</a></li><br>\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic/jsp/editProfile.jsp\">Update Profile</a></li><br>\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic//jsp/patientreport.jsp\">Upload Reports</a></li><br>\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic//jsp/fixapt.jsp\">Pending Appointments</a></li><br>\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic/Logoff\">Logout</a></li><br>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"width: 80%; height: 700px; float: left; background-image: url('/ediagnostic/images/docpat.jpg');\">\r\n");
      out.write("\t\t<form action=\"/ediagnostic/PatientReport\" method=\"post\" onsubmit=\"return main()\"  enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table border=\"0\" class=\"register\"\r\n");
      out.write("\t\t\t\tstyle=\"margin-top: 50px; margin-left: 80px; width: 520px;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>Select report document</th>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"file\" name=\"txtrep\" id=\"txtrep\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>WorkerId</th>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"text\" id=\"txtworkerid\" name=\"txtworkerid\"\r\n");
      out.write("\t\t\t\t\t\tvalue=");
      out.print(uid);
      out.write(" readonly=\"readonly\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\" id=\"msgid1\" style=\"color: red;font-size: small;\"></th>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>PatientName</th>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"text\" id=\"txtpatientname\" name=\"txtpatientname\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"enter patientname\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\" id=\"msgname\" style=\"color: red;font-size: small;\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>Testid</th>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"text\" id=\"txttestid\" name=\"txttestid\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"enter Testid\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\" id=\"msgid2\" style=\"color: red;font-size: small;\"></th>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>DoctorId</th>\r\n");
      out.write("\t\t\t\t\t<th><input type=\"text\" id=\"txtdoctorid\" name=\"txtdoctorid\" placeholder=\"enter doctorid\"></th>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\" id=\"msgid3\" style=\"color: red;font-size: small;\"></th>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>Remarks</th>\r\n");
      out.write("\t\t\t\t\t<th><textarea  id=\"txtremark\" name=\"txtremark\" placeholder=\"enter remarks\"></textarea></th>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\" id=\"msgremark\" style=\"color: red;font-size: small;\"></th>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t    <th>Status</th>\r\n");
      out.write("\t\t\t    <th><input type=\"text\" id=\"txtstatus\" name=\"txtstatus\" placeholder=\"enter remark\"></th>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\" id=\"msgstatus\" style=\"color: red;font-size: small;\"></th>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\"><button type=\"submit\">Submit</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"reset\">Reset</button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
