/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2018-08-01 06:09:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tips_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/html/doctor_menu.html", Long.valueOf(1533103360339L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Add Tips</title>\r\n");
      out.write("<script src=\"/ediagnostic/js/validation.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/ediagnostic/bootstrapfiles/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("<script src=\"/ediagnostic/bootstrapfiles/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/ediagnostic/bootstrapfiles/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function main() \r\n");
      out.write("{\r\n");
      out.write("\tvar title = document.getElementById(\"txttitle\").value;\r\n");
      out.write("\tvar contents = document.getElementById(\"txtcontents\").value;\r\n");
      out.write("\tvar b = true\r\n");
      out.write("\tif (checkEmpty(title) == false) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"msgtitle\").innerHTML = \"Please enter title of the tip\"\r\n");
      out.write("\t\tdocument.getElementById(\"txttitle\").focus()\r\n");
      out.write("\t\tb = false\r\n");
      out.write("\t}\r\n");
      out.write("\telse if (checkEmpty(title) == true) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"msgtitle\").innerHTML = \"\"\r\n");
      out.write("\t}\r\n");
      out.write("\tif (checkEmpty(contents) == false) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"msgcontents\").innerHTML = \"Please enter content of the tip\"\r\n");
      out.write("\t\tdocument.getElementById(\"txtcontents\").focus()\r\n");
      out.write("\t\tb = false\r\n");
      out.write("\t}\r\n");
      out.write("\telse if (checkEmpty(contents) == true) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"msgcontents\").innerHTML = \"\"\r\n");
      out.write("\t}\r\n");
      out.write("\treturn b\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tstyle=\"width: 100%; height: 80px; background-color: #6882d1; float: left\">\r\n");
      out.write("\t\t<h1 style=\"text-align: center;\">POST TIPS</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"width: 20%; height: 700px; float: left\">\r\n");
      out.write("\t\t");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Doctor Menu</title>\r\n");
      out.write("<style>\r\n");
      out.write("a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tstyle=\"width: 100%; height: 100%; background-color: yellow; float: left\">\r\n");
      out.write("\t\t<ul style=\"list-style-type: none;\">\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic/jsp/compose.jsp\">Compose</a></li><br>\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic/jsp/inbox.jsp\">Inbox</a></li><br>\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic/jsp/sentitems.jsp\">Sent Items</a></li><br>\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic/jsp/viewprofile.jsp\">View Profile</a></li><br>\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic/jsp/editProfile.jsp\">Update Profile</a></li><br>\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic//jsp/news.jsp\">Post News</a></li><br>\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic/jsp/tips.jsp\">Post Tips</a></li><br>\r\n");
      out.write("\t\t\t<li><a href=\"/ediagnostic/Logoff\">Log out</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tstyle=\"width: 80%; height: 700px; background-color: #28B0CD; float: left\">\r\n");
      out.write("\t\t<form action=\"/ediagnostic/AddTips1\" method=\"post\" onsubmit=\"return main()\">\r\n");
      out.write("\t\t<table style=\"margin-left: 400px; margin-top: 150px\">\r\n");
      out.write("\t\t<tr><th>Title</th><th><input type=\"text\" name=\"txttitle\" id=\"txttitle\"\r\n");
      out.write("\t\tplaceholder=\"Please enter title of the tip\"></th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr><td colspan=\"2\" id=\"msgtitle\" style=\"color: red\"></th></tr>\r\n");
      out.write("\t\t<tr><th>Contents</th><th><textarea name=\"txtcontents\" id=\"txtcontents\" rows=\"5\" placeholder=\"Please enter content of the tip\"></textarea></th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr><td colspan=\"2\" id=\"msgcontents\" style=\"color: red\"></th></tr>\r\n");
      out.write("\t\t<tr><td align=\"center\" colspan=2><button type=\"submit\">Submit</td></tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
